# Generated by Django 3.0.8 on 2020-08-01 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20200801_2121'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Courser',
            new_name='Course',
        ),
    ]
