# Generated by Django 3.0.8 on 2021-03-25 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20200812_1856'),
        ('courses', '0004_auto_20200829_1947'),
    ]

    operations = [
    ]
